<?php

namespace CoreBundle\Repository;

/**
 * BlopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlopRepository extends \Doctrine\ORM\EntityRepository
{
}
