<?php

namespace EspaceMembreBundle\Repository;

/**
 * ImageAllRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageAllRepository extends \Doctrine\ORM\EntityRepository
{
}
