<?php

namespace ForumBundle\Repository;

/**
 * CateAdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CateAdvertRepository extends \Doctrine\ORM\EntityRepository
{
}
