<?php

namespace ForumBundle\Repository;

/**
 * CommentAdvertTextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentAdvertTextRepository extends \Doctrine\ORM\EntityRepository
{
}
